backend:
  name: github
  branch: master
  repo: parnasiana/CEUSchile

media_folder: static/uploads
public_folder: "uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string", required: true}

