backend:
  name: github
  branch: master
  repo: parnasiana/CEUSchile

publish_mode: editorial_workflow

media_folder: static/img/uploads
public_folder: img/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título de entrada", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Borrador", name: "draft", widget: "boolean"}
      - {label: "Autor", name: "author", widget: "string"}:
          - {label: "Foto de autor", name: "image", widget: "image"}
          - {label: "'Nombre' 'Apellido Paterno' 'Apellido Materno'", name: "name", widget: "string"}
      - {label: "Imágen para entrada", name: "image", widget: "image"}
      - {label: "Escribe tu entrada", name: "entrada", widget: "markdown"}